// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	dropdownOptions: () => __TAURI_INVOKE<DropdownOption[]>("dropdown_options"),
	branchesList: (path: string) => typedError<Branch[], string>(__TAURI_INVOKE("branches_list", { path })),
	test: (text: string) => __TAURI_INVOKE<string>("test", { text }),
	commitList: (path: string, branch: string) => typedError<CommitInfo[], string>(__TAURI_INVOKE("commit_list", { path, branch })),
};

/* Types */
export type Branch = {
	name: string,
	is_head: boolean,
	commit_id: string,
	commit_message: string,
};

export type CommitInfo = {
	id: string,
	hash: string,
	author: string,
	message: string,
	time: string,
};

export type DropdownOption = {
	value: string,
	label: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

